version: '3.4'

services:
  github:
    image: github
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m flask run --no-debugger --no-reload --host 0.0.0.0 --port 8050"]
    ports:
      - 8050:8050
      - 5678:5678
    environment:
      - FLASK_APP=customer-analytics\src\scripts\dashboard.py
